"Term       <- _ Factor (Add / Sub)*\n"
"Add        <- '+' _ Factor\n"
"Sub        <- '-' _ Factor\n"
"Factor     <- Power (Mul / Div)*\n"
"Mul        <- '*' _ Power\n"
"Div        <- '/' _ Power\n"
"Power      <- Primary '^' _ Primary / Primary\n"
"Primary    <- (Parens / Function / NegateProb / Negative / Number / Variable) _\n"
"Parens     <- '(' Term ')'\n"
"Function   <- Exp / Log\n"
"Exp        <- 'exp' _ '(' _ Term _ ')' / 'e' _ '^' _ Primary\n"
"Log        <- 'log' _ '(' _ Term _ ')'\n"
"NegateProb <- '!' _ Primary\n"
"Negative   <- '-' _ Primary\n"
"Sign       <- < [-+]? > _\n"
"Number     <- Sign _ (Scientific / IntOrFloat)\n"
"IntOrFloat <- Float / Integer\n"
"Integer    <- ([0-9]+)\n"
"Float      <- Integer '.' Integer / '.' Integer\n"
"Scientific <- IntOrFloat ('e'/'E') Sign Integer\n"
"Variable   <- '$' identifier\n"
"identifier <- < [a-z] [a-z0-9]* >\n"
"~_          <- [ \t\r\n]*\n"
"\n"
