"Term       <- Factor (Add / Sub)*\n"
"Add        <- '+' Factor\n"
"Sub        <- '-' Factor\n"
"Factor     <- Power (Mul / Div)*\n"
"Mul        <- '*' Power\n"
"Div        <- '/' Power\n"
"Power      <- Primary '^' Primary / Primary\n"
"Primary    <- Parens / Function / NegateProb / Negative / Number / Variable\n"
"Parens     <- '(' Term ')'\n"
"Function   <- Exp / Log\n"
"Exp        <- 'exp' _ '(' _ Term _ ')' / 'e' _ '^' _ Primary\n"
"Log        <- 'log' _ '(' _ Term _ ')'\n"
"NegateProb <- '!' Primary\n"
"Negative   <- '-' Primary\n"
"Sign       <- < [-+]? > _\n"
"Number     <- Sign (Scientific / IntOrFloat)\n"
"IntOrFloat <- Float / Integer\n"
"Integer    <- ([0-9]+)\n"
"Float      <- Integer '.' Integer\n"
"Scientific <- IntOrFloat ('e'/'E') Sign Integer\n"
"Variable   <- '$' identifier\n"
"identifier <- < [a-z] [a-z0-9]* > _\n"
"~_          <- [ \t\r\n]*\n"
"\n"
