REGEX <- BEGIN_ANCHOR? REGEX_BODY END_ANCHOR*
REGEX_BODY <- NONEMPTY_REGEX_BODY /
NONEMPTY_REGEX_BODY <- END_ANCHOR NONEMPTY_REGEX_BODY / QUANT_SYMBOLS REGEX_BODY
BEGIN_ANCHOR <- '^'
END_ANCHOR <- '$'
QUANT_SYMBOLS <- QUANT_SYMBOL QUANT_SYMBOLS / QUANT_SYMBOL
QUANT_SYMBOL <- END_ANCHOR QUANTIFIER / SYMBOL QUANTIFIER / SYMBOL
SYMBOL <- NEGATED_CHAR_CLASS / CHAR_CLASS / IMPLICIT_CHAR_CLASS / ALTERNATION / LITERAL_CHAR
LITERAL_CHAR <- ESCAPED_CHAR / (!'$' .)
QUANTIFIER <- '*' / '+' / ('{' INTEGER '}') / ('{' INTEGER ',' INTEGER '}')
INTEGER <- [1-9] [0-9]*
CHAR_CLASS <- '[' CHARS ']'
NEGATED_CHAR_CLASS <- '[' '^' CHARS ']'
IMPLICIT_CHAR_CLASS <- PRESET_CHAR_CLASS
CHARS <- CHAR CHARS / CHAR
CHAR <- PRESET_CHAR_CLASS / CHAR_RANGE / SINGLE_CHAR
PRESET_CHAR_CLASS <- DIGIT_CHAR / WHITE_CHAR / NONWHITE_CHAR / WILD_CHAR
DIGIT_CHAR <- '\\d'
WHITE_CHAR <- '\\s'
NONWHITE_CHAR <- '\\S'
WILD_CHAR <- '.'
CHAR_RANGE <- SINGLE_CHAR '-' SINGLE_CHAR
SINGLE_CHAR <- ESCAPED_CHAR / (!']' .)
ESCAPED_CHAR <- '\\' [nrt|(\[\]\\]
/ '\\' [0-2][0-7][0-7]
/ '\\' [0-7][0-7]
ALTERNATION <- '(' ALT_OPTION ('|' ALT_OPTION)+ ')'
ALT_OPTION <- ALT_SYMBOL*
ALT_SYMBOL <- !'|' !')' SYMBOL
